### ISSUE TITLE
signup module

### ISSUE THREAD

**Issue by bhagi123** [xFran/TarSignup#5]
sir

i dont know how to use email part of code kindly help

**Comment by sridhar1218** [comment]
Hello Sir,

Greetings of the day,

How could i increase the session timeout more than 7200sec in zf2, So kindly help me.

Regards,
Sridhar

**Comment by xFran** [comment]
You can add 
    'session' => array(
        'remember_me_seconds' => 9999999,
    ),
in module.config.php
For more information: http://framework.zend.com/manual/current/en/modules/zend.session.config.html
